library(tidyverse)
library(forecast)
library(tseries)
library(lubridate)
head(hotel_bookings)
str(hotel_bookings)
summary(hotel_bookings)
colSums(is.na(hotel_bookings))
hotel_clean <- hotel_bookings %>% filter(is_canceled == 0)
hotel_clean <- hotel_clean %>% mutate(arrival_date = as.Date(paste(arrival_date_year,arrival_date_month,"01", sep = "-"),format = "%Y-%B-%d"))
monthly_demand <- hotel_clean %>% group_by(arrival_date) %>% summarise(bookings = n())
head(monthly_demand)
ggplot(monthly_demand, aes(x = arrival_date, y = bookings)) + geom_line(color = "steelblue", linewidth = 1) + labs(title = "Monthly Hotel Demand Over Time",x = "Date", y = "Number of Bookings") + theme_minimal()rint(monthly_demand)
hotel_ts <- ts(monthly_demand$bookings,start = c(2015, 7),frequency = 12)
print(hotel_ts)
plot(hotel_ts, main = "Hotel Demand Time Series",ylab = "Bookings", xlab = "Year")
adf.test(hotel_ts)
par(mfrow = c(1, 2))
acf(hotel_ts, main = "ACF Plot")
pacf(hotel_ts, main = "PACF Plot")
auto_arima_model <- auto.arima(hotel_ts,seasonal = TRUE,stepwise = FALSE,trace = TRUE)
summary(auto_arima_model)
forecast_result <- forecast(auto_arima_model, h = 12)
print(forecast_result)
plot(forecast_result,main = "Hotel Demand Forecast - Next 12 Months",xlab = "Year",ylab = "Number of Bookings",col = "steelblue")
checkresiduals(auto_arima_model)
png("hotel_forecast.png", width=800, height=500)
plot(forecast_result,main = "Hotel Demand Forecast - Next 12 Months",xlab = "Year",ylab = "Number of Bookings")
dev.off()
write.csv(as.data.frame(forecast_result),"hotel_forecast_results.csv")